version: "3.7"

services:

  worker1:
    build:
      context: ./
      dockerfile: ./worker1/Dockerfile
    env_file:
      - ./worker1/environment
    volumes:
      - ./worker1/src:/usr/src/app/src/
      - ./worker1/binding:/usr/src/app/binding/
      - ./node_modules:/usr/src/node_modules

  worker2:
    build:
      context: ./
      dockerfile: ./worker1/Dockerfile
    env_file:
      - ./worker2/environment
    volumes:
      - ./worker1/src:/usr/src/app/src/
      - ./worker2/binding:/usr/src/app/binding/
      - ./node_modules:/usr/src/node_modules

  worker3:
    build:
      context: ./
      dockerfile: ./worker1/Dockerfile
    env_file:
      - ./worker3/environment
    volumes:
      - ./worker1/src:/usr/src/app/src/
      - ./worker3/binding:/usr/src/app/binding/
      - ./node_modules:/usr/src/node_modules

  producer:
    build:
      context: ./
      dockerfile: ./producer/Dockerfile
    env_file:
      - ./producer/environment
    volumes:
      - ./producer/src:/usr/src/app/src/
      - ./producer/binding:/usr/src/app/binding/
      - ./node_modules:/usr/src/node_modules

  rabbitmq:
    image: "rabbitmq:management"
    logging:
      driver: none
    ports:
      - 15672:15672


